# Generated by Django 4.0.2 on 2022-06-21 11:10

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='photo',
            field=models.ImageField(blank=True, upload_to=app1.models.user_directory_path),
        ),
    ]
